name: 🚀 Conference talk
description: Submit your talk
labels: [talk]
body:
  - type: input
    attributes:
      label: Full name
      description: Your real name and surname.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Talk description
      description: A clear and concise description of the talk, timing (30-60 min), other format like masterclass or round table.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Contacts
      description: email, twitter, telegram, other contacts you have (optional).
  - type: textarea
    attributes:
      label: Relevant experience
      description: Add a few words abour your experience in public talks, links to video or articles, etc. (optional).
  - type: textarea
    attributes:
      label: Comments
      description: Add your comment in a free form. (optional).
